//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenModelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamentos()
        {
            this.Propietarios = new HashSet<Propietarios>();
        }
    
        public int IdApartamento { get; set; }
        public Nullable<decimal> NumeroApart { get; set; }
        public Nullable<int> Piso { get; set; }
        public Nullable<int> Bloque { get; set; }
        public Nullable<int> Unidad { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Unidad_recidencial Unidad_recidencial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Propietarios> Propietarios { get; set; }
    }
}
