//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenModelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int IDCompra { get; set; }
        public Nullable<int> IDMercado { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Mercados Mercados { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
