//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenModelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mercados()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public int IdMercado { get; set; }
        public Nullable<System.DateTime> FechaCracion { get; set; }
        public Nullable<int> IdPropietario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<bool> Creado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compras> Compras { get; set; }
        public virtual Propietarios Propietarios { get; set; }
    }
}
