//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenModelos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propietarios()
        {
            this.Mercados = new HashSet<Mercados>();
        }
    
        public int IdPropietario { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public Nullable<decimal> Telefono { get; set; }
        public Nullable<int> IDAparatamento { get; set; }
    
        public virtual Apartamentos Apartamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mercados> Mercados { get; set; }
    }
}
